import Head from 'next/head'

function Caldas({dados}) {
  return <>
    <Head>
          <title>Página do site Bruno</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
    <h1> Olá pessoal</h1>

    {console.log(dados)}
    <p>Os dados que vem da nossa API de parceiros são:</p>
        <h1>Parceiros</h1>
          {dados.map((dado) => ( <div key={dado.nome_parceiro}>
            <p><b>Nome do Parceiro:</b> {dado.nome_parceiro}</p>
            <p><b>Descrição:</b> {dado.descricao_parceiro}</p>
            <p><b>Site:</b> {dado.site_parceiro}</p>
            <hr></hr>
          </div>
          ) ) } .
  </>
}


export async function getStaticProps() {
  const res = await fetch('https://elos-be.herokuapp.com/api/parceiros/')
  const dados = await res.json();

  return {
    props: {
      dados
    }
  }
}

export default Caldas
