import Head from 'next/head'

export default function Caldas() {
  return <>
    <Head>
          <title>Página do site Bruno</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
    <h1> Olá pessoal
    </h1>
  </>
}