import Head from 'next/head'

import EventData from "./eventos";

export default function Eventos1() {
  return <>
  <Head>
        <title>Página do site Bruno</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <meta name="description" content="Site do abrigo de animais Kãotinho"/>
  <meta name="author" content="Alunos da UNIVESP - Eixo Computação - 2020"/>
  <link rel="stylesheet" type="text/css" href="/static/bootstrap/css/bootstrap.min.css"/>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossOrigin="anonymous"/>
      <link rel="stylesheet" type="text/css" href="/static/bootstrap/css/carousel.css" rel="stylesheet"/>
      <link rel="stylesheet" type="text/css" href="/static/bootstrap/css/blog.css"/>
      <link rel="stylesheet" type="text/css" href="/static/css/style.css"/>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"/>
      </Head>

        {/* <!-- Navbar --> */}
        <header id="barra-superior">
            
    {/* <!-- Barra de navegação --> */}
    <nav className="fixed-top navbar navbar-expand-lg navbar-light bg-white shadow justify-content-center m-0 px-0 py-0">
      <div className="container mx-2">
        {/* <!-- Logo e Título do site --> */}
        <a className="navbar-brand h1 mb-8" href="#">
            <img src="https://piunivesp.s3.sa-east-1.amazonaws.com/elos_de_amor/media/logo-elos_transparente.png" width="50" height="50" className="d-inline-block align-middle m-0 px-0 py-0" alt="logo"/>
            <spam className="align-middle" id="titulo">Elos de Amor</spam>
        </a>
        {/* <!-- Fim logo e título--> */}
        {/* <!-- Botão collased --> */}
        <button className="navbar-toggler m-0 p-0" type="button" data-bs-toggle="collapse" data-bs-target="#navbarMenu" aria-controls="navbarMenu" aria-expanded="false" aria-label="Toggle navigation">
            <spam className="navbar-toggler-icon"></spam>
        </button>
        {/* <!-- Fim botão --> */}
        {/* <!-- Menu -->   */}
        <div className="collapse navbar-collapse" id="navbarMenu">
          <ul className="navbar-nav">
            <li className="nav-item"><a className="nav-link active" aria-current="page" href="/abrigo/">Elos</a></li>
            <li className="nav-item"><a className="nav-link" href="/abrigo/parceiros">Parceiros</a></li>
            <li className="nav-item"><a className="nav-link" href="/abrigo/eventos">Projetos e Eventos</a></li>
            <li className="nav-item"><a className="nav-link" href="/abrigo/mural_animais">Blog</a></li>
          </ul>
          {/* <!-- Rede Social  --> */}
          <ul className="navbar-nav ml-auto">
            <li className="nav-item dropdown">
              <a className="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="navSocial">
                Social
              </a>
              <div className="dropdown-menu">
                <a className="dropdown-item" href="https://www.facebook.com/projetokaotinho" target="_blank">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" className="bi bi-facebook" viewBox="0 0 16 16">
                    <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
                  </svg>
                  Facebook
                </a>
                <a className="dropdown-item" href="https://www.instagram.com/projetokaotinho/" target="_blank">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" className="bi bi-instagram" viewBox="0 0 16 16">
                      <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
                  </svg>
                  Instagram
                </a>
                <a className="dropdown-item" href="https://vm.tiktok.com/ZM8xWD9QT/" target="_blank">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" className="bi bi-tiktok" viewBox="0 0 16 16">
                      <path d="M9 0h1.98c.144.715.54 1.617 1.235 2.512C12.895 3.389 13.797 4 15 4v2c-1.753 0-3.07-.814-4-1.829V11a5 5 0 1 1-5-5v2a3 3 0 1 0 3 3V0Z"/>
                  </svg>
                  TikTok
                </a>
                <a className="dropdown-item" href="https://twitter.com/kaotinho?s=20" target="_blank">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" className="bi bi-twitter" viewBox="0 0 16 16">
                      <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
                  </svg>
                  Twitter
                </a>
                <a className="dropdown-item" href="https://www.youtube.com/channel/UC3GfPZ9pe4yH_V1sCbZUqjA" target="_blank">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" className="bi bi-youtube" viewBox="0 0 16 16">
                      <path d="M8.051 1.999h.089c.822.003 4.987.033 6.11.335a2.01 2.01 0 0 1 1.415 1.42c.101.38.172.883.22 1.402l.01.104.022.26.008.104c.065.914.073 1.77.074 1.957v.075c-.001.194-.01 1.108-.082 2.06l-.008.105-.009.104c-.05.572-.124 1.14-.235 1.558a2.007 2.007 0 0 1-1.415 1.42c-1.16.312-5.569.334-6.18.335h-.142c-.309 0-1.587-.006-2.927-.052l-.17-.006-.087-.004-.171-.007-.171-.007c-1.11-.049-2.167-.128-2.654-.26a2.007 2.007 0 0 1-1.415-1.419c-.111-.417-.185-.986-.235-1.558L.09 9.82l-.008-.104A31.4 31.4 0 0 1 0 7.68v-.123c.002-.215.01-.958.064-1.778l.007-.103.003-.052.008-.104.022-.26.01-.104c.048-.519.119-1.023.22-1.402a2.007 2.007 0 0 1 1.415-1.42c.487-.13 1.544-.21 2.654-.26l.17-.007.172-.006.086-.003.171-.007A99.788 99.788 0 0 1 7.858 2h.193zM6.4 5.209v4.818l4.157-2.408L6.4 5.209z"/>
                  </svg>
                  YouTube
                </a>
              </div>
            </li>
          </ul>
        </div>
        {/* <!-- Fim Menu --> */}
      </div>
    </nav>
        </header>
        {/* <!-- Corpo Principal --> */}
        <div id="conteudo-principal">
            

    <div className="container-fluid">
    {/* <!-- Cabeçalho da página --> */}
      <div className="row justify-content-center jumbotron jumbotron-fluid bg-secondary mt-4 py-4">
        <div className="col-auto">
          <img className="univesp-kaotinho img-fluid rounded mx-auto d-block" src="https://piunivesp.s3.sa-east-1.amazonaws.com/media/evento2.svg" alt="Univesp e Kaotinho" width="90px"/>
        </div>
        <div className="col-md-8 text-white">
          <h2 className="display-5 font-italic">Projetos e Eventos</h2>
          <p className="lead">Participe dos Projetos e Eventos!</p>
        </div>
      {/* </div><!-- Fim do cabeçalho --> */}
    {/* <!-- Conteúdo Principal --> */}
      <div className="row justify-content-center mt-0">
        <div className="col-md-8 border-secondy justify-content-start">
          {/* <!-- Início do Accordion --> */}
          <div className="accordion" id="accordionExample">
            <div className="accordion-item">
              <h2 className="accordion-header" id="headingOne">
                <button className="accordion-button btn-secondary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                  Próximos Eventos
                </button>
              </h2>
              <div id="collapseOne" className="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                <div className="accordion-body">
                  
                  
                  {/* <!-- Início do cartão --> */}
                  <EventData/>
                  
                  
                        
                            
                          
                          </div>
                        </div>
                        <div className="m-1">
                          <a className="btn btn-secondary" href="https://www.google.com.br/maps/place/São Paulo" role="button" target="_blank">Como chegar</a>
                        </div>
                      </div>
                    </div>
                  </div>
                  
                  
                </div>
              </div>
            </div>
            <div className="accordion-item">
              <h2 className="accordion-header" id="headingTwo">
                <button className="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                  Eventos Vencidos
                </button>
              </h2>
              <div id="collapseTwo" className="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
                <div className="accordion-body">
                  
                  
                  
                  
                  
                </div>
              </div>
            </div>
          {/* </div><!-- Fim do Accordion --> */}

        {/* </div><!-- Fim row--> */}
      {/* </div><!-- Fim do Conteúdo principal --> */}

    </div>

        {/* <!-- Rodapé --> */}
        <footer id="barra-inferior">
            

    <div className="container">
      <div className="row navbar navbar-nav bg-white p-0  fixed-bottom">
        <div className="col">
          <span className="nav-item d-none d-md-block fs-6 fw-lighter align-middle text-center">
            Desenvolvido pelos alunos da UniVESP - Turma 2020 na disciplina de Projeto Integrador I
          </span>
        </div>
        <div className="col">
          <span className="nav-item fs-6 fw-lighter align-middle text-center p-0">
            <a className="nav-link" href="#">Voltar ao topo</a>
          </span>
        </div>
      </div>
    </div>
        </footer>

        {/* <!-- Principal JavaScript do Bootstrap */}
        {/* ================================================== --> */}
        {/* <!-- Foi colocado no final para a página carregar mais rápido --> */}
        {/* <!-- JavaScript (Opcional) --> */}
        {/* <!-- jQuery primeiro, depois Popper.js, depois Bootstrap JS --> */}
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossOrigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossOrigin="anonymous"></script>
        <script type="text/javascript" src="/static/bootstrap/js/bootstrap.bundle.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossOrigin="anonymous"></script>

  </>
}

